# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
