# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labexam',
            name='examination_id',
        ),
    ]
