# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0004_remove_examinacion_laboratorio_id'),
        ('labapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labexam',
            name='examinacion_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examenes_laboratorios', to='docapp.Examinacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labexam',
            name='laboratorio_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='labapp.Laboratorio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labexam',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
