# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('laboratory', 'Laboratory')], default='NA', max_length=20),
        ),
    ]
