# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('receptionist', 'Receptionista'), ('laboratory', 'Laboratorio')], max_length=20, null=True),
        ),
    ]
