# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181121_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar/default.png', null=True, upload_to='avatars/user_owner'),
        ),
    ]
