# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180728_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('laboratory', 'Laboratory')], max_length=20, null=True),
        ),
    ]
