# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180829_0544'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='receptionprofile',
            table='sm_recepcionistas',
        ),
    ]
