# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinacion',
            name='manejador_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinaciones', to='accounts.DoctorProfile'),
        ),
    ]
