# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteempresa',
            name='arl',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pacienteempresa',
            name='eps',
            field=models.CharField(default='sal', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pacienteempresa',
            name='fondo_pensiones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Afp',
        ),
        migrations.DeleteModel(
            name='Arl',
        ),
        migrations.DeleteModel(
            name='Eps',
        ),
    ]
