# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobaccidents',
            old_name='atentido',
            new_name='atendido',
        ),
        migrations.RemoveField(
            model_name='examtype',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='hazards',
            name='id',
        ),
        migrations.AddField(
            model_name='examtype',
            name='state',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('iniciado', 'Iniciado'), ('problemas', 'Problema'), ('finalizado', 'Finalizado')], default='pendient', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hazards',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hazards', serialize=False, to='docapp.AntecedentJobs'),
        ),
    ]
