# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examinacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('iniciado', 'Iniciado'), ('en problemas', 'En Problema'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pacienteempresa',
            name='numero_de_hijos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pacienteempresa',
            name='telefono',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pacienteparticular',
            name='telefono',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
