# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitoalcohol',
            old_name='alcohol',
            new_name='aplica',
        ),
        migrations.RenameField(
            model_name='habitocigarrillo',
            old_name='numbero_diarios',
            new_name='numero_diarios',
        ),
        migrations.RenameField(
            model_name='habitodroga',
            old_name='droga',
            new_name='aplica',
        ),
        migrations.RemoveField(
            model_name='habitocigarrillo',
            name='cigarette',
        ),
        migrations.AddField(
            model_name='habitocigarrillo',
            name='aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habitodroga',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitogenerales',
            name='acciones_en_tiempo_libre',
            field=models.TextField(),
        ),
    ]
