# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180728_1024'),
        ('docapp', '0002_auto_20180729_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.ReceptionProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='antecedentjobs',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='docapp.Person'),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='docapp.Person'),
        ),
    ]
