# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0002_remove_labexam_examination_id'),
        ('docapp', '0002_auto_20180826_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riesgos',
            old_name='empresa_id',
            new_name='antecedente_id',
        ),
        migrations.AddField(
            model_name='examinacion',
            name='laboratorio_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examinaciones', to='labapp.Laboratorio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='razon',
            field=models.TextField(default=''),
        ),
    ]
