# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0002_auto_20180915_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiometria',
            name='resultados_oidos',
            field=models.ImageField(blank=True, null=True, upload_to='otoscopia/%Y/%m/%d/'),
        ),
    ]
