# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0002_auto_20180814_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exposiciones',
            name='audiology',
        ),
        migrations.RenameField(
            model_name='antfamiliares',
            old_name='descripcion',
            new_name='observaciones',
        ),
        migrations.RenameField(
            model_name='otoscopia',
            old_name='otoscopia_der',
            new_name='otoscopia_derecho',
        ),
        migrations.RenameField(
            model_name='otoscopia',
            old_name='otoscopia_izq',
            new_name='otoscopia_izquierdo',
        ),
        migrations.RenameField(
            model_name='otrosantecedentes',
            old_name='otros',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='antfamiliares',
            name='otro_familiar',
        ),
        migrations.RemoveField(
            model_name='exposicionaudifonos',
            name='exposicion',
        ),
        migrations.RemoveField(
            model_name='exposicionautomotriz',
            name='exposicion',
        ),
        migrations.RemoveField(
            model_name='exposicionmaquinariapesada',
            name='exposicion',
        ),
        migrations.RemoveField(
            model_name='exposicionmotocicleta',
            name='exposicion',
        ),
        migrations.AddField(
            model_name='exposicionaudifonos',
            name='audiology',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exposicion_audifonos', to='docapp.Audiology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exposicionautomotriz',
            name='audiology',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exposicion_automotriz', to='docapp.Audiology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exposicionmaquinariapesada',
            name='audiology',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exposicion_maquinaria_pesada', to='docapp.Audiology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exposicionmotocicleta',
            name='audiology',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exposicion_motocicleta', to='docapp.Audiology'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Exposiciones',
        ),
    ]
