# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0002_auto_20180905_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Arl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arl', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pacienteempresa',
            name='arl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docapp.Arl'),
        ),
        migrations.AlterField(
            model_name='pacienteempresa',
            name='eps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docapp.Eps'),
        ),
        migrations.AlterField(
            model_name='pacienteempresa',
            name='fondo_pensiones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docapp.Afp'),
        ),
    ]
