# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0003_auto_20180915_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinacion',
            name='laboratorio_id',
        ),
    ]
