# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0003_auto_20180814_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposicionaudifonos',
            name='epa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionaudifonos',
            name='frecuencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionaudifonos',
            name='tiempo_exposicion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionaudifonos',
            name='tiempo_uso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionautomotriz',
            name='epa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionautomotriz',
            name='frecuencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionautomotriz',
            name='tiempo_exposicion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionautomotriz',
            name='tiempo_uso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionmaquinariapesada',
            name='epa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionmaquinariapesada',
            name='frecuencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionmaquinariapesada',
            name='tiempo_exposicion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionmaquinariapesada',
            name='tiempo_uso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionmotocicleta',
            name='epa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionmotocicleta',
            name='frecuencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionmotocicleta',
            name='tiempo_exposicion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposicionmotocicleta',
            name='tiempo_uso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
