# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0003_auto_20180826_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleexam',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examenes_internos', to='accounts.ReceptionProfile'),
        ),
    ]
