# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0003_auto_20180729_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobaccidents',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='docapp.AntecedentJobs'),
        ),
    ]
