# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0004_remove_examinacion_laboratorio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinacion',
            name='doctor_estado',
            field=models.CharField(choices=[('no asignado', 'No Asignado'), ('asignado', 'Asignado'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado')], default='no asignado', max_length=20),
        ),
        migrations.AddField(
            model_name='examinacion',
            name='lab_estado',
            field=models.CharField(choices=[('no asignado', 'No Asignado'), ('asignado', 'Asignado'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado')], default='no asignado', max_length=20),
        ),
        migrations.AlterField(
            model_name='examinacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
    ]
