# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0004_auto_20180814_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoactual',
            name='audiology',
        ),
        migrations.RemoveField(
            model_name='escucha',
            name='estado_actual',
        ),
        migrations.RemoveField(
            model_name='escucharuido',
            name='estado_actual',
        ),
        migrations.RemoveField(
            model_name='frasesrepetidas',
            name='estado_actual',
        ),
        migrations.RemoveField(
            model_name='ruidomolestia',
            name='estado_actual',
        ),
        migrations.RemoveField(
            model_name='volumentv',
            name='estado_actual',
        ),
        migrations.AddField(
            model_name='escucha',
            name='audiology',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estado_actual_escucha', to='docapp.Audiology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escucha',
            name='epa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escucha',
            name='frecuencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escucha',
            name='tiempo_exposicion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escucha',
            name='tiempo_uso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escucharuido',
            name='audiology',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estado_actual_escucha_ruido', to='docapp.Audiology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escucharuido',
            name='epa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escucharuido',
            name='frecuencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escucharuido',
            name='tiempo_exposicion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escucharuido',
            name='tiempo_uso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frasesrepetidas',
            name='audiology',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estado_actual_frases_repetidas', to='docapp.Audiology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frasesrepetidas',
            name='epa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frasesrepetidas',
            name='frecuencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frasesrepetidas',
            name='tiempo_exposicion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frasesrepetidas',
            name='tiempo_uso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruidomolestia',
            name='audiology',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estado_actual_ruido_molestia', to='docapp.Audiology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruidomolestia',
            name='epa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruidomolestia',
            name='frecuencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruidomolestia',
            name='tiempo_exposicion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruidomolestia',
            name='tiempo_uso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volumentv',
            name='audiology',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estado_actual_volumen_tv', to='docapp.Audiology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volumentv',
            name='epa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volumentv',
            name='frecuencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volumentv',
            name='tiempo_exposicion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volumentv',
            name='tiempo_uso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EstadoActual',
        ),
    ]
