# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0004_auto_20180829_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinacion',
            name='do_exam_altura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examinacion',
            name='do_exam_audiologia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examinacion',
            name='do_exam_visiometria',
            field=models.BooleanField(default=False),
        ),
    ]
