# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0005_auto_20180814_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antginecoobstetricos',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='antpersonalesfamiliares',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='conclusion',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='examfisicoabdomen',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='examfisicoaspectogeneral',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='examfisicoboca',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='examfisicocolumna',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='examfisicocorazon',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='examfisicocuello',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='examfisicoextremidades',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='examfisicogenitounitario',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='examfisiconariz',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='examfisiconeurologico',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='examfisicooidos',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='examfisicoojos',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='examfisicotoraxpulmones',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='habitoalcohol',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='habitocigarrillo',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='habitodroga',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RenameField(
            model_name='habitogenerales',
            old_name='occupational',
            new_name='ocupacional',
        ),
        migrations.RemoveField(
            model_name='antexamenexterno',
            name='otros_examenes',
        ),
        migrations.AlterField(
            model_name='occupational',
            name='tipo_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocupacional', to='docapp.TipoExamen'),
        ),
    ]
