# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('docapp', '0005_auto_20181118_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='activated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='accounts.ReceptionProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='accounts.DoctorProfile'),
        ),
    ]
