# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0006_auto_20180815_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agudeza',
            old_name='visiometry',
            new_name='visiometria',
        ),
        migrations.RenameField(
            model_name='ananmesis',
            old_name='audiology',
            new_name='audiologia',
        ),
        migrations.RenameField(
            model_name='antenfermedad',
            old_name='visiometry',
            new_name='visiometria',
        ),
        migrations.RenameField(
            model_name='antexamenexterno',
            old_name='visiometry',
            new_name='visiometria',
        ),
        migrations.RenameField(
            model_name='antfamiliares',
            old_name='audiology',
            new_name='audiologia',
        ),
        migrations.RenameField(
            model_name='antusolentes',
            old_name='visiometry',
            new_name='visiometria',
        ),
        migrations.RenameField(
            model_name='cronomatica',
            old_name='visiometry',
            new_name='visiometria',
        ),
        migrations.RenameField(
            model_name='escucha',
            old_name='audiology',
            new_name='audiologia',
        ),
        migrations.RenameField(
            model_name='escucharuido',
            old_name='audiology',
            new_name='audiologia',
        ),
        migrations.RenameField(
            model_name='exposicionaudifonos',
            old_name='audiology',
            new_name='audiologia',
        ),
        migrations.RenameField(
            model_name='exposicionautomotriz',
            old_name='audiology',
            new_name='audiologia',
        ),
        migrations.RenameField(
            model_name='exposicionmaquinariapesada',
            old_name='audiology',
            new_name='audiologia',
        ),
        migrations.RenameField(
            model_name='exposicionmotocicleta',
            old_name='audiology',
            new_name='audiologia',
        ),
        migrations.RenameField(
            model_name='frasesrepetidas',
            old_name='audiology',
            new_name='audiologia',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='audiology',
            new_name='audiologia',
        ),
        migrations.RenameField(
            model_name='otoscopia',
            old_name='audiology',
            new_name='audiologia',
        ),
        migrations.RenameField(
            model_name='otrosantecedentes',
            old_name='audiology',
            new_name='audiologia',
        ),
        migrations.RenameField(
            model_name='ruidomolestia',
            old_name='audiology',
            new_name='audiologia',
        ),
        migrations.RenameField(
            model_name='sintomas',
            old_name='visiometry',
            new_name='visiometria',
        ),
        migrations.RenameField(
            model_name='volumentv',
            old_name='audiology',
            new_name='audiologia',
        ),
    ]
