# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0006_auto_20181121_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultass', to='accounts.DoctorProfile'),
        ),
    ]
