# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0006_auto_20180803_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='audiome_id',
        ),
        migrations.RemoveField(
            model_name='otoscopia',
            name='audiome_id',
        ),
        migrations.AddField(
            model_name='information',
            name='audiometry',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='informacion', to='docapp.Audiometry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otoscopia',
            name='audiometry',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='otoscopia', to='docapp.Audiometry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otoscopia',
            name='otoscopia_der',
            field=models.ImageField(upload_to='otoscopia/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='otoscopia',
            name='otoscopia_izq',
            field=models.ImageField(upload_to='otoscopia/%Y/%m/%d/'),
        ),
    ]
