# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0007_auto_20180803_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agudeza',
            old_name='visio',
            new_name='visiometry',
        ),
        migrations.RenameField(
            model_name='ant_enfermedad',
            old_name='vision',
            new_name='visiometry',
        ),
        migrations.RenameField(
            model_name='ant_exam_externo',
            old_name='vision',
            new_name='visiometry',
        ),
        migrations.RenameField(
            model_name='ant_uso_lentes',
            old_name='vision',
            new_name='visiometry',
        ),
        migrations.RenameField(
            model_name='cronomatica',
            old_name='vision',
            new_name='visiometry',
        ),
        migrations.RemoveField(
            model_name='sintomas',
            name='vision',
        ),
        migrations.AddField(
            model_name='sintomas',
            name='visiometry',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to='docapp.Visiometry'),
            preserve_default=False,
        ),
    ]
