# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0007_auto_20180815_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examenes',
            old_name='nombre',
            new_name='nombre_examen',
        ),
        migrations.RenameField(
            model_name='examenes',
            old_name='laboratorio',
            new_name='nombre_laboratorio',
        ),
        migrations.RemoveField(
            model_name='examenes',
            name='resultado',
        ),
        migrations.AlterField(
            model_name='examensangre',
            name='tipo_de_sangre',
            field=models.CharField(choices=[('a', 'A'), ('b-', 'B'), ('o+', 'O'), ('ab-', 'AB')], max_length=5),
        ),
    ]
