# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0009_auto_20180803_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobaccidents',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='jobaccidents',
            name='work',
        ),
        migrations.AlterField(
            model_name='bloodexam',
            name='blood_type',
            field=models.CharField(choices=[('a', 'A'), ('b-', 'B'), ('ab-', 'AB'), ('o+', 'O')], max_length=5, verbose_name='tipo_sangre'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.DeleteModel(
            name='JobAccidents',
        ),
    ]
