# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0010_auto_20180809_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='KOH_unias_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='KOH_unias_lab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='KOH_unias_result',
            field=models.CharField(blank=True, choices=[('n', 'No aplica'), ('a', 'Aplica')], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='colesterol_hdi_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='colesterol_hdi_lab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='colesterol_hdi_result',
            field=models.CharField(blank=True, choices=[('n', 'No aplica'), ('a', 'Aplica')], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='colesterol_ldi_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='colesterol_ldi_lab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='colesterol_ldi_result',
            field=models.CharField(blank=True, choices=[('n', 'No aplica'), ('a', 'Aplica')], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='colesterol_total_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='colesterol_total_lab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='colesterol_total_result',
            field=models.CharField(blank=True, choices=[('n', 'No aplica'), ('a', 'Aplica')], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='coprologico_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='coprologico_lab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='coprologico_result',
            field=models.CharField(blank=True, choices=[('n', 'No aplica'), ('a', 'Aplica')], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='frotis_garganta_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='frotis_garganta_lab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='frotis_garganta_result',
            field=models.CharField(blank=True, choices=[('n', 'No aplica'), ('a', 'Aplica')], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='hemograma_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='hemograma_lab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='hemograma_result',
            field=models.CharField(blank=True, choices=[('n', 'No aplica'), ('a', 'Aplica')], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='serologia_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='serologia_lab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='serologia_result',
            field=models.CharField(blank=True, choices=[('n', 'No aplica'), ('a', 'Aplica')], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='trigliceridos_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='trigliceridos_lab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='trigliceridos_result',
            field=models.CharField(blank=True, choices=[('n', 'No aplica'), ('a', 'Aplica')], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='uroanalisis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='uroanalisis_lab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='uroanalisis_result',
            field=models.CharField(blank=True, choices=[('n', 'No aplica'), ('a', 'Aplica')], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='vdrl_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='vdrl_lab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='vdrl_result',
            field=models.CharField(blank=True, choices=[('n', 'No aplica'), ('a', 'Aplica')], default='n', max_length=1, null=True),
        ),
    ]
