# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='name',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('periodico', 'Periodico'), ('retiro', 'Retiro'), ('reubicacion', 'Re-Ubicacion'), ('post-incapacidad', 'Post-Incapacidad')], max_length=20),
        ),
    ]
