# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0002_auto_20180714_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personexamtype',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='personexamtype',
            name='person',
        ),
        migrations.RemoveField(
            model_name='examtype',
            name='persons',
        ),
        migrations.AddField(
            model_name='examtype',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='docapp.Person'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PersonExamType',
        ),
    ]
