# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0003_auto_20180714_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
